version: "3.8"

services:
  postgres:
    image: postgres
    container_name: api-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go-movies
      - POSTGRES_PASSWORD=Passw0rd
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-data:

